// Mocks generated by Mockito 5.4.6 from annotations
// in mqtt_scout/test/core/mqtt/subscription_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mqtt_scout/core/mqtt/i_mqtt_client.dart' as _i2;
import 'package:mqtt_scout/core/mqtt/models/mqtt_connection_state.dart' as _i5;
import 'package:mqtt_scout/domain/models/broker_profile.dart' as _i6;
import 'package:mqtt_scout/domain/models/mqtt_message.dart' as _i4;
import 'package:mqtt_scout/domain/models/subscription.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IMqttClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMqttClient extends _i1.Mock implements _i2.IMqttClient {
  MockIMqttClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.MqttMessage> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i3.Stream<_i4.MqttMessage>.empty(),
          )
          as _i3.Stream<_i4.MqttMessage>);

  @override
  _i3.Stream<_i5.MqttConnectionState> get connectionStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateStream),
            returnValue: _i3.Stream<_i5.MqttConnectionState>.empty(),
          )
          as _i3.Stream<_i5.MqttConnectionState>);

  @override
  _i3.Stream<String> get errorStream =>
      (super.noSuchMethod(
            Invocation.getter(#errorStream),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i5.MqttConnectionState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _i5.MqttConnectionState.disconnected,
          )
          as _i5.MqttConnectionState);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i6.MqttProtocolVersion get negotiatedVersion =>
      (super.noSuchMethod(
            Invocation.getter(#negotiatedVersion),
            returnValue: _i6.MqttProtocolVersion.v3_1_1,
          )
          as _i6.MqttProtocolVersion);

  @override
  _i3.Future<void> connect(_i6.BrokerProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> subscribe(_i7.Subscription? subscription) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [subscription]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> publish(
    String? topic,
    String? payload, {
    int? qos = 0,
    bool? retain = false,
    String? contentType,
    String? responseTopic,
    int? messageExpiryInterval,
    Map<String, String>? userProperties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publish,
              [topic, payload],
              {
                #qos: qos,
                #retain: retain,
                #contentType: contentType,
                #responseTopic: responseTopic,
                #messageExpiryInterval: messageExpiryInterval,
                #userProperties: userProperties,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearRetainedMessage(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#clearRetainedMessage, [topic]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
